# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default
  #vmImage: ubuntu-latest

stages:
  - stage: tfvalidate
    jobs:
      - job: validate 
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'terraform service connection'
              backendAzureRmResourceGroupName: 'terraform-stage'
              backendAzureRmStorageAccountName: 'stage4321'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraproject.state'
          - task: TerraformTaskV4@4
            displayName: Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'terraform service connection'
          - task: TerraformTaskV4@4
            displayName: destroy
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              environmentServiceNameAzureRM: 'terraform service connection'
